noinst_PROGRAMS =
noinst_PROGRAMS += test-postal-device
noinst_PROGRAMS += test-postal-service
noinst_PROGRAMS += test-url-router

TEST_PROGS += test-postal-device
TEST_PROGS += test-postal-service
TEST_PROGS += test-url-router

test_postal_device_SOURCES = tests/test-postal-device.c
test_postal_device_CPPFLAGS = $(JSON_CFLAGS) -I$(top_srcdir) -I$(top_srcdir)/mongo-glib
test_postal_device_LDADD = libpostal.la

test_postal_service_SOURCES = tests/test-postal-service.c
test_postal_service_CPPFLAGS = $(JSON_CFLAGS) -I$(top_srcdir) -I$(top_srcdir)/mongo-glib
test_postal_service_LDADD = libpostal.la

test_url_router_SOURCES = tests/test-url-router.c
test_url_router_CPPFLAGS = -I$(top_srcdir) $(SOUP_CFLAGS)
test_url_router_LDADD = libpostal.la
